# Generated by Django 4.2.29 on 2026-03-31 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_product_image_product_link_product_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="images",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="product",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
