# Generated by Django 4.2.29 on 2026-03-31 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="product",
            name="link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.FloatField(default=4.5),
        ),
        migrations.AlterField(
            model_name="product",
            name="count",
            field=models.IntegerField(default=1),
        ),
    ]
